app/models.py
from flask_login import UserMixin
from flask_sqlalchemy import SQLAlchemy
from sqlalchemy.schema import Column, ForeignKey, Table
from sqlalchemy.types import Integer, String, Float, Enum
from sqlalchemy.orm import relationship
from werkzeug.security import generate_password_hash, check_password_hash

db = SQLAlchemy()

order_details = Table(
    "order_details",
    db.Model.metadata,
    Column("menu_item_id", ForeignKey("menu_items.id"), primary_key=True),
    Column("order_id", ForeignKey("orders.id"), primary_key=True)
)

class Employee(db.Model, UserMixin):
    __tablename__ = 'employees'

    id = Column('id', Integer, primary_key=True)
    name = Column('name', String(100), nullable=False)
    employee_number = Column('employee_number', Integer, nullable=False, unique=True)
    hashed_password = Column('hashed_password', String(255), nullable=False)

    @property
    def password(self):
        return self.hashed_password
    
    @password.setter
    def password(self, password):
        self.hashed_password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)
    

class Menu(db.Model):
    __tablename__ = 'menus'

    id = Column(Integer, primary_key=True)
    name = Column(String(30), nullable=False)

    menu_items = relationship("MenuItem", back_populates="menu")


class MenuItem(db.Model):
    __tablename__ = 'menu_items'

    id = Column(Integer, primary_key=True)
    name = Column(String(50), nullable=False)
    price = Column(Float, nullable=False)
    menu_id = Column(Integer, ForeignKey('menus.id'), nullable=False)
    menu_type_id = Column(Integer, ForeignKey('menu_item_types.id'), nullable=False)

    type = relationship("MenuItemType", back_populates="menu_items")
    menu = relationship("Menu", back_populates="menu_items")
    orders = relationship("Order",
                          secondary=order_details,
                          back_populates="menu_items")
    

class MenuItemType(db.Model):
    __tablename__ = 'menu_item_types'

    id = Column(Integer, primary_key=True)
    name = Column(String(20), nullable=False)

    menu_items = relationship("MenuItem", back_populates="type")


class Table(db.Model):
    __tablename__ = 'tables'

    id = Column(Integer, primary_key=True)
    number = Column(Integer, nullable=False, unique=True)
    capacity = Column(Integer, nullable=False)


class Order(db.Model):
    __tablename__ = 'orders'

    id = Column(Integer, primary_key=True)
    table_id = Column(Integer, ForeignKey('tables.id'), nullable=False)
    server_id = Column(Integer, ForeignKey('employees.id'), nullable=False)
    price = Column(Integer, nullable=False)
    status = Column(Enum("Active", "Ended"), nullable=False)

    menu_items = relationship("MenuItem",
                              secondary=order_details,
                              back_populates="orders")

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    employee_number = StringField('Employee number', validators=[DataRequired()])
    password = PasswordField('Password', validators=[DataRequired()])
    submit = SubmitField('Login')

app/__init__.py
from flask import Flask
from flask_login import LoginManager
from .config import Configuration
from .models import db, Employee
from .routes import orders, session

#! App
app = Flask(__name__)
app.config.from_object(Configuration)
app.register_blueprint(orders.bp)
app.register_blueprint(session.bp)
db.init_app(app)

#! Login Manager
login = LoginManager(app)
login.login_view = "session.login"

@login.user_loader
def load_user(id):
    return Employee.query.get(int(id))

app/routes/orders.py
from flask import Blueprint, render_template
from flask_login import login_required
bp = Blueprint("orders", __name__, url_prefix="")


@bp.route("/")
@login_required
def index():
    return render_template("orders.html")

app/routes/session.py
from app.forms import LoginForm
from app.models import Employee
from flask import Blueprint, redirect, url_for, render_template
from flask_login import current_user, login_user, logout_user
bp = Blueprint("session", __name__, url_prefix="/session")


@bp.route("/", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect(url_for("orders.index"))
    form = LoginForm()
    if form.validate_on_submit():
        empl_number = form.employee_number.data
        employee = Employee.query.filter(Employee.employee_number == empl_number).first()
        if not employee or not employee.check_password(form.password.data):
            return redirect(url_for(".login"))
        login_user(employee)
        return redirect(url_for("orders.index"))
    return render_template("login.html", form=form)

@bp.route('/logout', methods=["POST"])
def logout():
    logout_user()
    return redirect(url_for('.login'))

app/templates/base.html
<html>
    <head>
        {% if title %}
            <title>{{ title }} - Order Up!</title>
        {% else %}
            <title>Welcome to Order Up!</title>
        {% endif %}
    </head>
    <body>
        {% if not current_user.is_anonymous %}
            <form action="{{ url_for('session.logout') }}" method="post">
                <button>Logout</button>
            </form>
        {% endif %}
        {% block content %}{% endblock %}
    </body>
</html>

app/templates/login.html
{% extends "base.html" %}

{% block content %}
<form method="post" action="{{ url_for('.login') }}">
    {{ form.csrf_token }}
    <div>
        {{ form.employee_number.label }} {{ form.employee_number }}

        {% if form.employee_number.errors %}
            <ul>
                {% for error in form.employee_number.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <div>
        {{ form.password.label }} {{ form.password }}

        {% if form.employee_number.errors %}
            <ul>
                {% for error in form.employee_number.errors %}
                    <li>{{ error }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    </div>
    <div>{{ form.submit }}</div>
</form>
{% endblock %}

app/templates/orders.html
{% extends "base.html" %}

{% block content %}
    <h1>Order Up!</h1>
{% endblock %}